Repository TanPhu123/WebBanHang, pull requests merged in 2023-05, with the labels that each got.

#49 Statiscial Management
  DetailOrder.cshtml
  Index.cshtml
  SaleChart.cshtml
  ThongKe.cshtml
Labels: Tấn Phú, Done, 8 Điểm

#46 Logout
  TaiKhoanController.cs
Labels: Tấn Phú, Done, 2 Điểm

#43 ProductSearch
  TimKiemController.cs
  getTimKiem.cshtml
Labels: 3 Điểm, Tấn Phú, Done

#41 OnlinePayment
  PayPalModel.cs
  PaymentOnline.cshtml
Labels: 3 Điểm, Thiên Lý, Done

#40 MakeOrders
  GioHangController.cs
  HeaderCart.cshtml
Labels: Tấn Phú, Done, 8 Điểm

#39 ProductList
  ProductMenuController.cs
  ProductModel.cs
Labels: 3 Điểm

#38 View HomePage
  About.cshtml
  Contact.cshtml
  HomeController.cs
  LienHe.cshtml
  SeeAll.cshtml
  Success.cshtml
  TinTuc.cshtml
  newProduct.cshtml
Labels: 3 Điểm, Anh Nhật, Done

#36 Registaion
  Error.cshtml
  Lockout.cshtml
  _Layout.cshtml
  _LoginPartial.cshtml
  _MyLayout.cshtml
Labels: Done

#35 User management
  DangNhaps/Index.cshtml
  DangNhapsController.cs
Labels: 8 Điểm

#31 revenue management
  HoaDon/DetailOrder.cshtml
  HoaDon/Index.cshtml
  HoaDon/SaleChart.cshtml
  HoaDon/ThongKe.cshtml
Labels: Thiên Lý, Done

#30 detail_product
  Product/Detail.cshtml
Labels: Done

#51 Product Reviews
  Index.cshtml
  getProduct.cshtml
Labels: 3 Điểm, Tấn Phú, Done

#52 Staticial
  HomesController.cs
  QuanLyDanhThuController.cs
Labels: 3 Điểm, Anh Nhật, Done

#53 User Management
  DangNhapsController.cs
Labels: 3 Điểm, Thiên Lý, Done

#54 Add files via upload
  Create.cshtml
  Delete.cshtml
  Details.cshtml
  Edit.cshtml
  Index.cshtml
  NewsController.cs
Labels: Tấn Phú, Done, 8 Điểm

#55 View Product History
  Index.cshtml
Labels: Done, 2 Điểm

#56 Feedback about purchased product
  ConfirmEmail.cshtml
  ExternalLoginConfirmation.cshtml
  ExternalLoginFailure.cshtml
  ForgotPassword.cshtml
  ForgotPasswordConfirmation.cshtml
  Login.cshtml
  Register.cshtml
  ResetPassword.cshtml
  ResetPasswordConfirmation.cshtml
  SendCode.cshtml
  VerifyCode.cshtml
  _ExternalLoginsListPartial.cshtml
Labels: 3 Điểm, Thiên Lý, Done
